<?php 
get_header();
?>
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<h1>Servicios</h1>	
<?php
get_footer();
?>